{
  "responseHeader":{
    "status":0,
    "QTime":47,
    "params":{
      "q":"biological_sample_id:83599"}},
  "response":{"numFound":399,"start":0,"docs":[
      {
        "date_of_experiment":"2012-08-21T00:00:00Z",
        "date_of_birth":"2012-05-07T00:00:00Z",
        "weight_date":"2012-08-21T00:00:00Z",
        "id":"50906935",
        "datasource_id":22,
        "datasource_name":"IMPC",
        "project_id":10,
        "project_name":"BaSH",
        "pipeline_name":"MGP Select Pipeline",
        "pipeline_stable_id":"MGP_001",
        "procedure_stable_id":"IMPC_BWT_001",
        "procedure_group":"IMPC_BWT",
        "parameter_stable_id":"IMPC_BWT_001_001",
        "data_type":"FLOAT",
        "pipeline_id":8,
        "procedure_id":1,
        "parameter_id":1,
        "strain_accession_id":"MGI:2159965",
        "strain_name":"C57BL/6N",
        "genetic_background":"involves: C57BL/6N",
        "allelic_composition":"Rab15<tm1a(KOMP)Wtsi>/Rab15<tm1a(KOMP)Wtsi>",
        "experiment_source_id":"105991207",
        "gene_symbol":"Rab15",
        "gene_accession_id":"MGI:1916865",
        "experiment_id":3049437,
        "phenotyping_center_id":3,
        "phenotyping_center":"WTSI",
        "specimen_project_id":8,
        "specimen_project_name":"MGP",
        "production_center_id":3,
        "production_center":"WTSI",
        "litter_id":"201668",
        "observation_type":"unidimensional",
        "colony_id":"MEAW",
        "biological_sample_id":83599,
        "biological_model_id":41539,
        "zygosity":"homozygote",
        "sex":"female",
        "biological_sample_group":"experimental",
        "data_point":32.9,
        "external_sample_id":"1146783",
        "parameter_name":"Body weight",
        "procedure_name":"Body Weight",
        "metadata_group":"d41d8cd98f00b204e9800998ecf8427e",
        "metadata":["Equipment ID = Ohaus",
          "Equipment manufacturer = Ohaus",
          "Equipment model = Adventurer Pro",
          "Experimenter ID = 8E98D"],
        "allele_accession_id":"MGI:4363640",
        "allele_symbol":"Rab15<tm1a(KOMP)Wtsi>",
        "weight_parameter_stable_id":"IMPC_BWT_001_001",
        "weight_days_old":106,
        "weight":32.9,
        "developmental_stage_acc":"EFO:0002948",
        "developmental_stage_name":"postnatal",
        "age_in_days":106,
        "age_in_weeks":15,
        "_version_":1652532349241393155},
      {
        "date_of_experiment":"2012-08-14T00:00:00Z",
        "date_of_birth":"2012-05-07T00:00:00Z",
        "weight_date":"2012-08-14T00:00:00Z",
        "id":"50905158",
        "datasource_id":22,
        "datasource_name":"IMPC",
        "project_id":10,
        "project_name":"BaSH",
        "pipeline_name":"MGP Select Pipeline",
        "pipeline_stable_id":"MGP_001",
        "procedure_stable_id":"IMPC_BWT_001",
        "procedure_group":"IMPC_BWT",
        "parameter_stable_id":"IMPC_BWT_001_001",
        "data_type":"FLOAT",
        "pipeline_id":8,
        "procedure_id":1,
        "parameter_id":1,
        "strain_accession_id":"MGI:2159965",
        "strain_name":"C57BL/6N",
        "genetic_background":"involves: C57BL/6N",
        "allelic_composition":"Rab15<tm1a(KOMP)Wtsi>/Rab15<tm1a(KOMP)Wtsi>",
        "experiment_source_id":"105019893",
        "gene_symbol":"Rab15",
        "gene_accession_id":"MGI:1916865",
        "experiment_id":3049292,
        "phenotyping_center_id":3,
        "phenotyping_center":"WTSI",
        "specimen_project_id":8,
        "specimen_project_name":"MGP",
        "production_center_id":3,
        "production_center":"WTSI",
        "litter_id":"201668",
        "observation_type":"unidimensional",
        "colony_id":"MEAW",
        "biological_sample_id":83599,
        "biological_model_id":41539,
        "zygosity":"homozygote",
        "sex":"female",
        "biological_sample_group":"experimental",
        "data_point":32.4,
        "external_sample_id":"1146783",
        "parameter_name":"Body weight",
        "procedure_name":"Body Weight",
        "metadata_group":"d41d8cd98f00b204e9800998ecf8427e",
        "metadata":["Equipment ID = Ohaus",
          "Equipment manufacturer = Ohaus",
          "Equipment model = Adventurer Pro",
          "Experimenter ID = 8F121"],
        "allele_accession_id":"MGI:4363640",
        "allele_symbol":"Rab15<tm1a(KOMP)Wtsi>",
        "weight_parameter_stable_id":"IMPC_DXA_001_001",
        "weight_days_old":99,
        "weight":32.4,
        "developmental_stage_acc":"EFO:0002948",
        "developmental_stage_name":"postnatal",
        "age_in_days":99,
        "age_in_weeks":14,
        "_version_":1652532349244538880},
      {
        "date_of_experiment":"2012-07-23T00:00:00Z",
        "date_of_birth":"2012-05-07T00:00:00Z",
        "weight_date":"2012-07-23T00:00:00Z",
        "id":"50909945",
        "datasource_id":22,
        "datasource_name":"IMPC",
        "project_id":10,
        "project_name":"BaSH",
        "pipeline_name":"MGP Select Pipeline",
        "pipeline_stable_id":"MGP_001",
        "procedure_stable_id":"IMPC_BWT_001",
        "procedure_group":"IMPC_BWT",
        "parameter_stable_id":"IMPC_BWT_001_001",
        "data_type":"FLOAT",
        "pipeline_id":8,
        "procedure_id":1,
        "parameter_id":1,
        "strain_accession_id":"MGI:2159965",
        "strain_name":"C57BL/6N",
        "genetic_background":"involves: C57BL/6N",
        "allelic_composition":"Rab15<tm1a(KOMP)Wtsi>/Rab15<tm1a(KOMP)Wtsi>",
        "experiment_source_id":"101937464",
        "gene_symbol":"Rab15",
        "gene_accession_id":"MGI:1916865",
        "experiment_id":3049695,
        "phenotyping_center_id":3,
        "phenotyping_center":"WTSI",
        "specimen_project_id":8,
        "specimen_project_name":"MGP",
        "production_center_id":3,
        "production_center":"WTSI",
        "litter_id":"201668",
        "observation_type":"unidimensional",
        "colony_id":"MEAW",
        "biological_sample_id":83599,
        "biological_model_id":41539,
        "zygosity":"homozygote",
        "sex":"female",
        "biological_sample_group":"experimental",
        "data_point":30.4,
        "external_sample_id":"1146783",
        "parameter_name":"Body weight",
        "procedure_name":"Body Weight",
        "metadata_group":"d41d8cd98f00b204e9800998ecf8427e",
        "metadata":["Equipment ID = Ohaus",
          "Equipment manufacturer = Ohaus",
          "Equipment model = Adventurer Pro",
          "Experimenter ID = 0D318"],
        "allele_accession_id":"MGI:4363640",
        "allele_symbol":"Rab15<tm1a(KOMP)Wtsi>",
        "weight_parameter_stable_id":"IMPC_BWT_001_001",
        "weight_days_old":77,
        "weight":30.4,
        "developmental_stage_acc":"EFO:0002948",
        "developmental_stage_name":"postnatal",
        "age_in_days":77,
        "age_in_weeks":11,
        "_version_":1652532349300113415},
      {
        "date_of_experiment":"2012-08-28T00:00:00Z",
        "date_of_birth":"2012-05-07T00:00:00Z",
        "weight_date":"2012-08-28T00:00:00Z",
        "id":"50925550",
        "datasource_id":22,
        "datasource_name":"IMPC",
        "project_id":8,
        "project_name":"MGP",
        "pipeline_name":"MGP Select Pipeline",
        "pipeline_stable_id":"MGP_001",
        "procedure_stable_id":"IMPC_HWT_001",
        "procedure_group":"IMPC_HWT",
        "parameter_stable_id":"IMPC_HWT_008_001",
        "data_type":"FLOAT",
        "pipeline_id":8,
        "procedure_id":71,
        "parameter_id":2443,
        "strain_accession_id":"MGI:2159965",
        "strain_name":"C57BL/6N",
        "genetic_background":"involves: C57BL/6N",
        "allelic_composition":"Rab15<tm1a(KOMP)Wtsi>/Rab15<tm1a(KOMP)Wtsi>",
        "experiment_source_id":"EXP330609",
        "gene_symbol":"Rab15",
        "gene_accession_id":"MGI:1916865",
        "experiment_id":3050729,
        "phenotyping_center_id":3,
        "phenotyping_center":"WTSI",
        "specimen_project_id":8,
        "specimen_project_name":"MGP",
        "production_center_id":3,
        "production_center":"WTSI",
        "litter_id":"201668",
        "observation_type":"unidimensional",
        "colony_id":"MEAW",
        "biological_sample_id":83599,
        "biological_model_id":41539,
        "zygosity":"homozygote",
        "sex":"female",
        "biological_sample_group":"experimental",
        "data_point":130.0,
        "external_sample_id":"1146783",
        "parameter_name":"Heart weight",
        "procedure_name":"Heart Weight",
        "metadata_group":"9b9c86eb507368735074dbf8e37a664e",
        "metadata":["Date of sacrifice = 2012-08-28T00:00:00Z",
          "Method of sacrifice = Ketamine (100mg/kg)/Xylazine (10mg/kg)",
          "Equipment ID = 18003728",
          "Equipment manufacturer = Sartorius AG Germany",
          "Equipment model = TE212",
          "Experimenter ID = 8E98D"],
        "allele_accession_id":"MGI:4363640",
        "allele_symbol":"Rab15<tm1a(KOMP)Wtsi>",
        "weight_parameter_stable_id":"IMPC_BWT_001_001",
        "weight_days_old":113,
        "weight":33.2,
        "developmental_stage_acc":"EFO:0002948",
        "developmental_stage_name":"postnatal",
        "age_in_days":113,
        "age_in_weeks":16,
        "_version_":1652532349682843652},
      {
        "date_of_experiment":"2012-08-28T00:00:00Z",
        "date_of_birth":"2012-05-07T00:00:00Z",
        "weight_date":"2012-08-28T00:00:00Z",
        "id":"50942248",
        "datasource_id":22,
        "datasource_name":"IMPC",
        "project_id":8,
        "project_name":"MGP",
        "pipeline_name":"MGP Select Pipeline",
        "pipeline_stable_id":"MGP_001",
        "procedure_stable_id":"IMPC_HEM_001",
        "procedure_group":"IMPC_HEM",
        "parameter_stable_id":"IMPC_HEM_006_001",
        "data_type":"FLOAT",
        "pipeline_id":8,
        "procedure_id":62,
        "parameter_id":2276,
        "strain_accession_id":"MGI:2159965",
        "strain_name":"C57BL/6N",
        "genetic_background":"involves: C57BL/6N",
        "allelic_composition":"Rab15<tm1a(KOMP)Wtsi>/Rab15<tm1a(KOMP)Wtsi>",
        "experiment_source_id":"330766",
        "gene_symbol":"Rab15",
        "gene_accession_id":"MGI:1916865",
        "experiment_id":3051795,
        "phenotyping_center_id":3,
        "phenotyping_center":"WTSI",
        "specimen_project_id":8,
        "specimen_project_name":"MGP",
        "production_center_id":3,
        "production_center":"WTSI",
        "litter_id":"201668",
        "observation_type":"unidimensional",
        "colony_id":"MEAW",
        "biological_sample_id":83599,
        "biological_model_id":41539,
        "zygosity":"homozygote",
        "sex":"female",
        "biological_sample_group":"experimental",
        "data_point":14.45,
        "external_sample_id":"1146783",
        "parameter_name":"Mean corpuscular hemoglobin",
        "procedure_name":"Hematology",
        "metadata_group":"c5d5b3349a0014cdac742fb284d786ed",
        "metadata":["Equipment ID = scil Vet abc hematology analyzer",
          "Equipment manufacturer = Scil animal care company Gmbh",
          "Equipment model = Scil Vet abc",
          "Anesthesia used for blood collection = Injection narcosis with Ketamine (100mg/kg)/Xylazine (10mg/kg)",
          "Method of blood collection = Retro-orbital puncture",
          "Anticoagulant = EDTA",
          "Blood collection tubes = Kabe Labortechnik 200ul EDTA",
          "Date and time of sacrifice = 2012-08-28T09:33:00+01:00",
          "Samples kept on ice between collection and analysis = No",
          "ID for blood collection SOP = ESLIM_024_001",
          "Date and time of blood collection = 2012-08-28T09:33:00+01:00",
          "Date of measurement = 2012-08-28",
          "Chip card number = Mouse Card (E0401091230)",
          "Storage temperature from blood collection until measurement = 18-22",
          "Blood analysis experimenter ID = 4E4B5",
          "Blood collection experimenter ID = 68CE1"],
        "allele_accession_id":"MGI:4363640",
        "allele_symbol":"Rab15<tm1a(KOMP)Wtsi>",
        "weight_parameter_stable_id":"IMPC_BWT_001_001",
        "weight_days_old":113,
        "weight":33.2,
        "developmental_stage_acc":"EFO:0002948",
        "developmental_stage_name":"postnatal",
        "age_in_days":113,
        "age_in_weeks":16,
        "_version_":1652532349912481800},
      {
        "date_of_experiment":"2012-08-14T00:00:00Z",
        "date_of_birth":"2012-05-07T00:00:00Z",
        "weight_date":"2012-08-14T00:00:00Z",
        "id":"50961160",
        "datasource_id":22,
        "datasource_name":"IMPC",
        "project_id":8,
        "project_name":"MGP",
        "pipeline_name":"MGP Select Pipeline",
        "pipeline_stable_id":"MGP_001",
        "procedure_stable_id":"IMPC_ABR_001",
        "procedure_group":"IMPC_ABR",
        "parameter_stable_id":"IMPC_ABR_010_001",
        "data_type":"FLOAT",
        "pipeline_id":8,
        "procedure_id":54,
        "parameter_id":1913,
        "strain_accession_id":"MGI:2159965",
        "strain_name":"C57BL/6N",
        "genetic_background":"involves: C57BL/6N",
        "allelic_composition":"Rab15<tm1a(KOMP)Wtsi>/Rab15<tm1a(KOMP)Wtsi>",
        "experiment_source_id":"EXP328973",
        "gene_symbol":"Rab15",
        "gene_accession_id":"MGI:1916865",
        "experiment_id":3053204,
        "phenotyping_center_id":3,
        "phenotyping_center":"WTSI",
        "specimen_project_id":8,
        "specimen_project_name":"MGP",
        "production_center_id":3,
        "production_center":"WTSI",
        "litter_id":"201668",
        "observation_type":"unidimensional",
        "colony_id":"MEAW",
        "biological_sample_id":83599,
        "biological_model_id":41539,
        "zygosity":"homozygote",
        "sex":"female",
        "biological_sample_group":"experimental",
        "data_point":20.0,
        "external_sample_id":"1146783",
        "parameter_name":"24kHz-evoked ABR Threshold",
        "procedure_name":"Auditory Brain Stem Response",
        "metadata_group":"943455a4fcea80e972922465b87304bc",
        "metadata":["Tone Pip Duration = 5",
          "Tone Pip rise/fall = 1",
          "Repetition Rate = 42.6",
          "Number averages = 256",
          "Recording Environment = In sound attenuating booth on thermo-statically controlled heating pad (@ 37°C)",
          "Anesthetic agent 1 = Ketamine",
          "Anesthetic agent 2 = Xylazine",
          "Anesthetic agent 1 dosage = 0.11",
          "Anesthetic agent 2 dosage = 0.011",
          "Anesthetic administration route = Intraperitoneal",
          "Date of Test = 2012-08-14T10:34:00Z",
          "Time of injection = 10:34:00",
          "Equipment ID = Sanger_RSF_1",
          "Equipment manufacturer = TDT (Tucker Davis Technologies)",
          "Equipment model = RP2.1 based system, RA4PA Medusa Preamplifier",
          "Software = Sanger bespoke averager software",
          "Experimenter ID = 8F121"],
        "allele_accession_id":"MGI:4363640",
        "allele_symbol":"Rab15<tm1a(KOMP)Wtsi>",
        "weight_parameter_stable_id":"IMPC_DXA_001_001",
        "weight_days_old":99,
        "weight":32.4,
        "developmental_stage_acc":"EFO:0002948",
        "developmental_stage_name":"postnatal",
        "age_in_days":99,
        "age_in_weeks":14,
        "_version_":1652532350465081349},
      {
        "date_of_experiment":"2012-08-14T00:00:00Z",
        "date_of_birth":"2012-05-07T00:00:00Z",
        "weight_date":"2012-08-14T00:00:00Z",
        "id":"50961028",
        "datasource_id":22,
        "datasource_name":"IMPC",
        "project_id":8,
        "project_name":"MGP",
        "pipeline_name":"MGP Select Pipeline",
        "pipeline_stable_id":"MGP_001",
        "procedure_stable_id":"IMPC_ABR_001",
        "procedure_group":"IMPC_ABR",
        "parameter_stable_id":"IMPC_ABR_006_001",
        "data_type":"FLOAT",
        "pipeline_id":8,
        "procedure_id":54,
        "parameter_id":1909,
        "strain_accession_id":"MGI:2159965",
        "strain_name":"C57BL/6N",
        "genetic_background":"involves: C57BL/6N",
        "allelic_composition":"Rab15<tm1a(KOMP)Wtsi>/Rab15<tm1a(KOMP)Wtsi>",
        "experiment_source_id":"EXP328973",
        "gene_symbol":"Rab15",
        "gene_accession_id":"MGI:1916865",
        "experiment_id":3053204,
        "phenotyping_center_id":3,
        "phenotyping_center":"WTSI",
        "specimen_project_id":8,
        "specimen_project_name":"MGP",
        "production_center_id":3,
        "production_center":"WTSI",
        "litter_id":"201668",
        "observation_type":"unidimensional",
        "colony_id":"MEAW",
        "biological_sample_id":83599,
        "biological_model_id":41539,
        "zygosity":"homozygote",
        "sex":"female",
        "biological_sample_group":"experimental",
        "data_point":15.0,
        "external_sample_id":"1146783",
        "parameter_name":"12kHz-evoked ABR Threshold",
        "procedure_name":"Auditory Brain Stem Response",
        "metadata_group":"943455a4fcea80e972922465b87304bc",
        "metadata":["Tone Pip Duration = 5",
          "Tone Pip rise/fall = 1",
          "Repetition Rate = 42.6",
          "Number averages = 256",
          "Recording Environment = In sound attenuating booth on thermo-statically controlled heating pad (@ 37°C)",
          "Anesthetic agent 1 = Ketamine",
          "Anesthetic agent 2 = Xylazine",
          "Anesthetic agent 1 dosage = 0.11",
          "Anesthetic agent 2 dosage = 0.011",
          "Anesthetic administration route = Intraperitoneal",
          "Date of Test = 2012-08-14T10:34:00Z",
          "Time of injection = 10:34:00",
          "Equipment ID = Sanger_RSF_1",
          "Equipment manufacturer = TDT (Tucker Davis Technologies)",
          "Equipment model = RP2.1 based system, RA4PA Medusa Preamplifier",
          "Software = Sanger bespoke averager software",
          "Experimenter ID = 8F121"],
        "allele_accession_id":"MGI:4363640",
        "allele_symbol":"Rab15<tm1a(KOMP)Wtsi>",
        "weight_parameter_stable_id":"IMPC_DXA_001_001",
        "weight_days_old":99,
        "weight":32.4,
        "developmental_stage_acc":"EFO:0002948",
        "developmental_stage_name":"postnatal",
        "age_in_days":99,
        "age_in_weeks":14,
        "_version_":1652532350591959046},
      {
        "date_of_experiment":"2012-08-14T00:00:00Z",
        "date_of_birth":"2012-05-07T00:00:00Z",
        "weight_date":"2012-08-14T00:00:00Z",
        "id":"50982231",
        "datasource_id":22,
        "datasource_name":"IMPC",
        "project_id":8,
        "project_name":"MGP",
        "pipeline_name":"MGP Select Pipeline",
        "pipeline_stable_id":"MGP_001",
        "procedure_stable_id":"IMPC_DXA_001",
        "procedure_group":"IMPC_DXA",
        "parameter_stable_id":"IMPC_DXA_001_001",
        "data_type":"FLOAT",
        "pipeline_id":8,
        "procedure_id":57,
        "parameter_id":2026,
        "strain_accession_id":"MGI:2159965",
        "strain_name":"C57BL/6N",
        "genetic_background":"involves: C57BL/6N",
        "allelic_composition":"Rab15<tm1a(KOMP)Wtsi>/Rab15<tm1a(KOMP)Wtsi>",
        "experiment_source_id":"EXP328929",
        "gene_symbol":"Rab15",
        "gene_accession_id":"MGI:1916865",
        "experiment_id":3054398,
        "phenotyping_center_id":3,
        "phenotyping_center":"WTSI",
        "specimen_project_id":8,
        "specimen_project_name":"MGP",
        "production_center_id":3,
        "production_center":"WTSI",
        "litter_id":"201668",
        "observation_type":"unidimensional",
        "colony_id":"MEAW",
        "biological_sample_id":83599,
        "biological_model_id":41539,
        "zygosity":"homozygote",
        "sex":"female",
        "biological_sample_group":"experimental",
        "data_point":32.4,
        "external_sample_id":"1146783",
        "parameter_name":"Body weight",
        "procedure_name":"Body Composition (DEXA lean/fat)",
        "metadata_group":"1f0313a8a852318ae73c07c4d6ff42e0",
        "metadata":["Equipment ID = Densitometer",
          "Equipment manufacturer = GE Medical Systems",
          "Equipment model = Lunar Piximus II",
          "Mouse Status = Anesthetized",
          "Anesthesia = Ketamine+Xylazine",
          "Experimenter ID = 996A7"],
        "allele_accession_id":"MGI:4363640",
        "allele_symbol":"Rab15<tm1a(KOMP)Wtsi>",
        "weight_parameter_stable_id":"IMPC_DXA_001_001",
        "weight_days_old":99,
        "weight":32.4,
        "developmental_stage_acc":"EFO:0002948",
        "developmental_stage_name":"postnatal",
        "age_in_days":99,
        "age_in_weeks":14,
        "_version_":1652532350902337544},
      {
        "date_of_experiment":"2012-08-14T00:00:00Z",
        "date_of_birth":"2012-05-07T00:00:00Z",
        "weight_date":"2012-08-14T00:00:00Z",
        "id":"50982459",
        "datasource_id":22,
        "datasource_name":"IMPC",
        "project_id":8,
        "project_name":"MGP",
        "pipeline_name":"MGP Select Pipeline",
        "pipeline_stable_id":"MGP_001",
        "procedure_stable_id":"IMPC_DXA_001",
        "procedure_group":"IMPC_DXA",
        "parameter_stable_id":"IMPC_DXA_005_001",
        "data_type":"FLOAT",
        "pipeline_id":8,
        "procedure_id":57,
        "parameter_id":2030,
        "strain_accession_id":"MGI:2159965",
        "strain_name":"C57BL/6N",
        "genetic_background":"involves: C57BL/6N",
        "allelic_composition":"Rab15<tm1a(KOMP)Wtsi>/Rab15<tm1a(KOMP)Wtsi>",
        "experiment_source_id":"EXP328929",
        "gene_symbol":"Rab15",
        "gene_accession_id":"MGI:1916865",
        "experiment_id":3054398,
        "phenotyping_center_id":3,
        "phenotyping_center":"WTSI",
        "specimen_project_id":8,
        "specimen_project_name":"MGP",
        "production_center_id":3,
        "production_center":"WTSI",
        "litter_id":"201668",
        "observation_type":"unidimensional",
        "colony_id":"MEAW",
        "biological_sample_id":83599,
        "biological_model_id":41539,
        "zygosity":"homozygote",
        "sex":"female",
        "biological_sample_group":"experimental",
        "data_point":0.4106,
        "external_sample_id":"1146783",
        "parameter_name":"Bone Mineral Content (excluding skull)",
        "procedure_name":"Body Composition (DEXA lean/fat)",
        "metadata_group":"1f0313a8a852318ae73c07c4d6ff42e0",
        "metadata":["Equipment ID = Densitometer",
          "Equipment manufacturer = GE Medical Systems",
          "Equipment model = Lunar Piximus II",
          "Mouse Status = Anesthetized",
          "Anesthesia = Ketamine+Xylazine",
          "Experimenter ID = 996A7"],
        "allele_accession_id":"MGI:4363640",
        "allele_symbol":"Rab15<tm1a(KOMP)Wtsi>",
        "weight_parameter_stable_id":"IMPC_DXA_001_001",
        "weight_days_old":99,
        "weight":32.4,
        "developmental_stage_acc":"EFO:0002948",
        "developmental_stage_name":"postnatal",
        "age_in_days":99,
        "age_in_weeks":14,
        "_version_":1652532350923309057},
      {
        "date_of_experiment":"2012-07-10T00:00:00Z",
        "date_of_birth":"2012-05-07T00:00:00Z",
        "weight_date":"2012-07-10T00:00:00Z",
        "id":"55434805",
        "datasource_id":22,
        "datasource_name":"IMPC",
        "project_id":8,
        "project_name":"MGP",
        "pipeline_name":"MGP Select Pipeline",
        "pipeline_stable_id":"MGP_001",
        "procedure_stable_id":"IMPC_GRS_001",
        "procedure_group":"IMPC_GRS",
        "parameter_stable_id":"IMPC_GRS_008_001",
        "data_type":"FLOAT",
        "pipeline_id":8,
        "procedure_id":39,
        "parameter_id":1533,
        "strain_accession_id":"MGI:2159965",
        "strain_name":"C57BL/6N",
        "genetic_background":"involves: C57BL/6N",
        "allelic_composition":"Rab15<tm1a(KOMP)Wtsi>/Rab15<tm1a(KOMP)Wtsi>",
        "experiment_source_id":"derived_IMPC_GRS_008_001_32791",
        "gene_symbol":"Rab15",
        "gene_accession_id":"MGI:1916865",
        "experiment_id":3986389,
        "phenotyping_center_id":3,
        "phenotyping_center":"WTSI",
        "specimen_project_id":8,
        "specimen_project_name":"MGP",
        "production_center_id":3,
        "production_center":"WTSI",
        "litter_id":"201668",
        "observation_type":"unidimensional",
        "colony_id":"MEAW",
        "biological_sample_id":83599,
        "biological_model_id":41539,
        "zygosity":"homozygote",
        "sex":"female",
        "biological_sample_group":"experimental",
        "data_point":93.197,
        "external_sample_id":"1146783",
        "parameter_name":"Forelimb grip strength measurement mean",
        "procedure_name":"Grip Strength",
        "metadata_group":"216fb750fec90b455e2384c60ebb76c6",
        "metadata":["Equipment ID = GRIPTEST V3.11",
          "Equipment manufacturer = Bioseb",
          "Grid model = HMGU plate",
          "Equipment model = Bio-GT3+MR"],
        "allele_accession_id":"MGI:4363640",
        "allele_symbol":"Rab15<tm1a(KOMP)Wtsi>",
        "weight_parameter_stable_id":"IMPC_BWT_001_001",
        "weight_days_old":64,
        "weight":29.5,
        "developmental_stage_acc":"EFO:0002948",
        "developmental_stage_name":"postnatal",
        "age_in_days":64,
        "age_in_weeks":9,
        "_version_":1652532393462988803}]
  }}
